version = 0.1

[default.deploy.parameters]
stack_name = "evrenthia-dev"
resolve_s3 = true
s3_prefix = "evrenthia-dev"
region = "us-east-2"
profile = "evrenthia-admin"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "EnvironmentName=\"dev\" FunctionNamePrefix=\"Evrenthia-Dev\" LogRetentionDays=\"14\" PushDeliveryMode=\"DRY_RUN\""
image_repositories = []

[default.global.parameters]
region = "us-east-2"

[prod.deploy.parameters]
stack_name = "evrenthia-prod"
resolve_s3 = true
s3_prefix = "evrenthia-prod"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "EnvironmentName=\"prod\" FunctionNamePrefix=\"Evrenthia-Prod\" LogRetentionDays=\"30\" PushDeliveryMode=\"DRY_RUN\""
image_repositories = []

[prod.global.parameters]
region = "us-east-2"
